version: "3.9"
services:
  reposilite:
    image: dzikoysk/reposilite:3.5.14
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Xmx128M ${JAVA_COMPOSE_OPTS}
      - REPOSILITE_OPTS= ${REPOSILITE_COMPOSE_OPTS}
      #- REPOSILITE_OPTS=--token admin:secret ${REPOSILITE_COMPOSE_OPTS}
    volumes:
      #- reposilite-data:/app/data
      - ~/reposilite-data:/app/data
    restart: unless-stopped
    stdin_open: true
    tty: true
  caddy:
    image: caddy:2.8.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config
      - caddy-data:/data
    restart: unless-stopped
volumes:
  #reposilite-data: {}
  caddy-config: {}
  caddy-data: {}